# Generated by Django 4.2.13 on 2024-08-02 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_patient_blood_group_alter_patient_patient_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_age',
            field=models.IntegerField(blank=True, null=True, verbose_name='zipcode'),
        ),
    ]
