# Generated by Django 4.2.13 on 2024-08-02 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_patient_patient_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='disease',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='zipcode'),
        ),
    ]
