# Generated by Django 4.2.13 on 2024-08-05 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_patient_disease'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='doctor_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='zipcode'),
        ),
    ]
