# Generated by Django 4.2.13 on 2024-08-05 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_patient_doctor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='mobile_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='zipcode'),
        ),
        migrations.AddField(
            model_name='patient',
            name='on_date',
            field=models.DateField(blank=True, null=True, verbose_name='zipcode'),
        ),
    ]
