# Generated by Django 4.2.13 on 2024-08-09 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_invoice_blood_group_alter_invoice_disease_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='mobile_number',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
