# Generated by Django 4.2.13 on 2024-08-12 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_uploadreport_alter_invoice_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadreport',
            name='report_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='uploadreport',
            name='upload_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='uploadreport',
            name='patient_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='uploadreport',
            name='reports',
            field=models.FileField(null=True, upload_to='patient_report/'),
        ),
    ]
